# Generated by Django 4.2.3 on 2023-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
