# Generated by Django 4.2.3 on 2023-07-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_activity_id_alter_activityuser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entityactivity',
            name='code_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entite'),
        ),
    ]
