# Generated by Django 4.2.3 on 2023-08-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_parent_alter_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloturation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EstClose', models.CharField(default='Oui', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='semaine',
            name='closed',
        ),
        migrations.AddField(
            model_name='charge',
            name='cloture',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.cloturation'),
            preserve_default=False,
        ),
    ]
