# Generated by Django 4.2.3 on 2023-08-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cloturation_remove_semaine_closed_charge_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturation',
            name='semaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.semaine'),
            preserve_default=False,
        ),
    ]
