# Generated by Django 4.2.3 on 2023-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cloturation_semaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityactivity',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='entityactivity',
            name='fin',
        ),
        migrations.AddField(
            model_name='entityactivity',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
