# Generated by Django 4.2.3 on 2023-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_entityactivity_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloturation',
            name='semaine',
        ),
    ]
