# Generated by Django 4.2.3 on 2023-08-01 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_cloturation_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 14, 23, 2, 748807, tzinfo=datetime.timezone.utc)),
        ),
    ]
