# Generated by Django 4.2.3 on 2023-08-02 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_charge_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 2, 52, 59, 850917, tzinfo=datetime.timezone.utc)),
        ),
    ]
