# Generated by Django 4.2.3 on 2023-08-02 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_activity_end_alter_activity_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 2, 53, 12, 40660, tzinfo=datetime.timezone.utc)),
        ),
    ]
