# Generated by Django 4.2.3 on 2023-08-02 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_charge_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 2, 58, 9, 820886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='charge',
            name='modify_date',
            field=models.DateField(),
        ),
    ]
