# Generated by Django 4.2.3 on 2023-08-02 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_charge_insert_date_alter_charge_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityactivity',
            name='duration',
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 3, 4, 58, 591597, tzinfo=datetime.timezone.utc)),
        ),
    ]
