# Generated by Django 4.2.3 on 2023-08-03 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_charge_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 4, 9, 59, 958846, tzinfo=datetime.timezone.utc)),
        ),
    ]
