# Generated by Django 4.2.3 on 2023-08-03 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_alter_charge_insert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturation',
            name='SemaineClose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.semaine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloturation',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 12, 24, 26, 358307, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cloturation',
            name='EstClose',
            field=models.CharField(default='Non', max_length=100),
        ),
    ]
