# Generated by Django 4.2.3 on 2023-08-03 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_cloturation_semaineclose_cloturation_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='cloture',
        ),
        migrations.RemoveField(
            model_name='cloturation',
            name='EstClose',
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 12, 47, 42, 623164, tzinfo=datetime.timezone.utc)),
        ),
    ]
