# Generated by Django 4.2.3 on 2023-08-15 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_projectfermé_alter_charge_insert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfermé',
            name='description',
            field=models.CharField(default='projet', max_length=100),
        ),
        migrations.AddField(
            model_name='projectfermé',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 16, 30, 3, 287679)),
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 15, 30, 3, 288678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectfermé',
            name='dateFemeture',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 16, 30, 3, 287679)),
        ),
    ]
