# Generated by Django 4.2.3 on 2023-08-15 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_projectfermé_description_projectfermé_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFerme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomProjet', models.CharField(max_length=100)),
                ('start', models.DateField(default=datetime.datetime(2023, 8, 15, 16, 31, 22, 104656))),
                ('description', models.CharField(default='projet', max_length=100)),
                ('dateFemeture', models.DateField(default=datetime.datetime(2023, 8, 15, 16, 31, 22, 104656))),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectFermé',
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 15, 31, 22, 105653, tzinfo=datetime.timezone.utc)),
        ),
    ]
