# Generated by Django 4.2.3 on 2023-08-16 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_projectferme_delete_projectfermé_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomProjet', models.CharField(max_length=100)),
                ('start', models.DateField(default=datetime.datetime(2023, 8, 16, 13, 16, 3, 922112))),
                ('description', models.CharField(default='projet', max_length=100)),
                ('dateFemeture', models.DateField(default=datetime.datetime(2023, 8, 16, 13, 16, 3, 922112))),
                ('motif', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 12, 16, 3, 922112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectferme',
            name='dateFemeture',
            field=models.DateField(default=datetime.datetime(2023, 8, 16, 13, 16, 3, 922112)),
        ),
        migrations.AlterField(
            model_name='projectferme',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 8, 16, 13, 16, 3, 922112)),
        ),
    ]
