# Generated by Django 4.2.4 on 2023-08-20 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_waitingproject_alter_charge_insert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 17, 43, 1, 437113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectferme',
            name='dateFemeture',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 43, 1, 429117)),
        ),
        migrations.AlterField(
            model_name='projectferme',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 43, 1, 429117)),
        ),
        migrations.AlterField(
            model_name='waitingproject',
            name='dateFemeture',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 43, 1, 429117)),
        ),
        migrations.AlterField(
            model_name='waitingproject',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 43, 1, 429117)),
        ),
    ]
