# Generated by Django 4.2.4 on 2023-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForgottenPasswordMailling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ForgotMail', models.CharField(max_length=100)),
            ],
        ),
    ]
